#SET @hour := -1;

#SELECT (@hour := @hour + 1) as HOUR,
#(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) as COUNT FROM ANIMAL_OUTS
#WHERE @hour < 23;

WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM HOUR_TABLE WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOUR_TABLE
    LEFT OUTER JOIN ANIMAL_OUTS
    ON HOUR(DATETIME) = HOUR_TABLE.HOUR
GROUP BY HOUR
ORDER BY HOUR ASC
